version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:7173"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__prueba=Server=db;Port=3306;Database=testdb;User=root;Password=db123;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db123
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
